#!/usr/bin/env bash
##──────────────────────────────────────────────────────────────
## sync-env.sh — pull MCP credentials from tofu output
##
## Reads api_url and demo credentials from the infra/ OpenTofu
## state and writes a .env file for the MCP server.
##
## Prerequisites:
##   sudo apt-get install -y jq
##──────────────────────────────────────────────────────────────
set -euo pipefail

INFRA_DIR="$(cd "$(dirname "$0")/../../infra" && pwd)"
ENV_FILE="$(cd "$(dirname "$0")" && pwd)/.env"

echo "▸ Reading tofu outputs from ${INFRA_DIR}…"

API_BASE_URL=$(cd "$INFRA_DIR" && tofu output -raw api_url)

CREDS_JSON=$(cd "$INFRA_DIR" && tofu output -json demo_credentials)
MCP_EMAIL=$(echo "$CREDS_JSON" | jq -r 'keys[0]')
MCP_PASSWORD=$(echo "$CREDS_JSON" | jq -r '.[keys[0]]')

cat > "$ENV_FILE" <<EOF
# ── Auto-generated by sync-env.sh — do not edit manually ────
# Re-run:  bash ./sync-env.sh   (or make sync-env-mcp)

ONBOARDYOU_API_URL='${API_BASE_URL}'
ONBOARDYOU_MCP_EMAIL='${MCP_EMAIL}'
ONBOARDYOU_MCP_PASSWORD='${MCP_PASSWORD}'
EOF

echo "✓ Wrote ${ENV_FILE}"
