#!/usr/bin/env bash
##──────────────────────────────────────────────────────────────
## sync-env.sh — pull live config + demo credentials from tofu
##
## Usage: ./sync-env.sh [-local]
##──────────────────────────────────────────────────────────────
set -euo pipefail

# Initialize flags
USE_LOCAL=false

# Simple argument parser
for arg in "$@"; do
  case $arg in
    -local|--local)
      USE_LOCAL=true
      shift
      ;;
  esac
done

INFRA_DIR="$(cd "$(dirname "$0")/../../../infra" && pwd)"
ENV_FILE="$(cd "$(dirname "$0")" && pwd)/.env"

echo "▸ Reading tofu outputs from ${INFRA_DIR}…"

API_BASE_URL=$(cd "$INFRA_DIR" && tofu output -raw api_url)

# Set FRONTEND_URL based on the -local flag
if [ "$USE_LOCAL" = true ]; then
    echo "  ! Local flag detected: forcing localhost URL."
    FRONTEND_URL="http://localhost:5174"
else
    # Query tofu, fall back to localhost if the output is missing
    FRONTEND_URL=$(cd "$INFRA_DIR" && tofu output -raw frontend_url 2>/dev/null || echo 'http://localhost:5174')
fi

# demo_credentials logic remains the same
CREDS_JSON=$(cd "$INFRA_DIR" && tofu output -json demo_credentials)
DEMO_EMAIL=$(echo "$CREDS_JSON" | jq -r 'keys[0]')
DEMO_PASSWORD=$(echo "$CREDS_JSON" | jq -r '.[keys[0]]')

cat > "$ENV_FILE" <<EOF
# ── Auto-generated by sync-env.sh — do not edit manually ────
# Re-run:  pnpm sync-env   (or ./sync-env.sh)

VITE_API_BASE_URL='${API_BASE_URL}'
VITE_MOCK_MODE=false
VITE_REMOTE_URL='${FRONTEND_URL}'
EOF

echo "✓ Wrote ${ENV_FILE}"
echo ""
echo "  Remote URL → ${FRONTEND_URL}"
echo "  Demo login → ${DEMO_EMAIL}"
echo "  Password   → ${DEMO_PASSWORD}"