#!/usr/bin/env bash
##──────────────────────────────────────────────────────────────
## sync-env.sh — pull live config + demo credentials from tofu
##
## Reads api_url and demo_credentials from the infra/ OpenTofu
## state and writes a .env file that Vite picks up automatically.
##
## Prerequisites:
##   sudo apt-get install -y jq
##──────────────────────────────────────────────────────────────
set -euo pipefail

INFRA_DIR="$(cd "$(dirname "$0")/../../../infra" && pwd)"
ENV_FILE="$(cd "$(dirname "$0")" && pwd)/.env"

echo "▸ Reading tofu outputs from ${INFRA_DIR}…"

API_BASE_URL=$(cd "$INFRA_DIR" && tofu output -raw api_url)

# frontend hosting URL (cloudfront) used by module federation when
# running the platform in production.  fall back to localhost dev server
# in case the output isn't available (e.g. before first deploy).
# Use tofu to query the same outputs as the other values.
FRONTEND_URL=$(cd "$INFRA_DIR" && tofu output -raw frontend_url 2>/dev/null || echo '')

# demo_credentials is a sensitive map { email = password }
# Extract the first entry for the demo login.
CREDS_JSON=$(cd "$INFRA_DIR" && tofu output -json demo_credentials)
DEMO_EMAIL=$(echo "$CREDS_JSON" | jq -r 'keys[0]')
DEMO_PASSWORD=$(echo "$CREDS_JSON" | jq -r '.[keys[0]]')

cat > "$ENV_FILE" <<EOF
# ── Auto-generated by sync-env.sh — do not edit manually ────
# Re-run:  pnpm sync-env   (or ./sync-env.sh)

VITE_API_BASE_URL='${API_BASE_URL}'
VITE_MOCK_MODE=false
VITE_REMOTE_URL='${FRONTEND_URL:-http://localhost:5174}'

# ── Demo user credentials (pre-filled on the login form) ─────
VITE_DEMO_EMAIL='${DEMO_EMAIL}'
VITE_DEMO_PASSWORD='${DEMO_PASSWORD}'
EOF

echo "✓ Wrote ${ENV_FILE}"
echo ""
echo "  Demo login → ${DEMO_EMAIL}"
echo "  Password   → ${DEMO_PASSWORD}"
