#[derive(Debug, serde::Serialize, serde::Deserialize)]
pub struct OpenapiDynamicApiResponse {
    /// Output schema generated by the egress strategy.
    pub output_schema: serde_json::Value,

    /// Path in the output schema body (eg data.items) => {data: {items: []}}
    pub output_schema_body_path : String,
}