#!/usr/bin/env bash
##──────────────────────────────────────────────────────────────
## sync-env.sh — pull live config + demo credentials from tofu
##
## Usage: ./sync-env.sh [-local]
##──────────────────────────────────────────────────────────────
set -euo pipefail

INFRA_DIR="$(cd "$(dirname "$0")/../infra" && pwd)"
WORKING_DIR="$(pwd)"
ENV_FILE="${WORKING_DIR}/.env"

echo "▸ Reading tofu outputs from ${INFRA_DIR}…"

API_BASE_URL=$(cd "$INFRA_DIR" && tofu output -raw api_url)
FRONTEND_URL=$(cd "$INFRA_DIR" && tofu output -raw frontend_url 2>/dev/null || echo 'http://localhost:5174')

# Extract path component from FRONTEND_URL for Vite base path.
# e.g. https://user.github.io/OnboardYou → /OnboardYou
# e.g. https://d1234.cloudfront.net        → (empty)
# Special-case GitHub Pages URLs: always use /OnboardYou when the domain contains github.io
# and append the path to the remote URL so it points at the deployed site.
if echo "$FRONTEND_URL" | grep -q "github.io"; then
    # ensure trailing slash removed then add /onboardyou
    FRONTEND_URL="$(echo "$FRONTEND_URL" | sed 's|/*$||')/OnboardYou"
    BASE_PATH="/OnboardYou"
elif [ "$FRONTEND_URL" = "*" ]; then
    echo "  ! Local flag detected: forcing localhost URL."
    FRONTEND_URL="http://localhost:5174"
    BASE_PATH=$(echo "$FRONTEND_URL" | sed 's|https\?://[^/]*||; s|/$||')
fi

cat > "$ENV_FILE" <<EOF
# ── Auto-generated by sync-env.sh — do not edit manually ────
# Re-run:  pnpm sync-env   (or ./sync-env.sh)

VITE_API_BASE_URL='${API_BASE_URL}'
VITE_MOCK_MODE=false
VITE_REMOTE_URL='${FRONTEND_URL}'
VITE_BASE_PATH='${BASE_PATH}'
EOF

echo "✓ Wrote ${ENV_FILE}"
echo ""
echo "  Remote URL → ${FRONTEND_URL}"