#!/usr/bin/env bash
##──────────────────────────────────────────────────────────────
## sync-env.sh — pull demo credentials from tofu output
##
## Reads api_url, demo_email, and demo_password from the
## infra/ OpenTofu state and writes a .env file for the
## smoke-test suite.
##
## Prerequisites:
##   sudo apt-get install -y jq
##──────────────────────────────────────────────────────────────
set -euo pipefail

INFRA_DIR="$(cd "$(dirname "$0")/../../../infra" && pwd)"
ENV_FILE="$(cd "$(dirname "$0")" && pwd)/.env"

echo "▸ Reading tofu outputs from ${INFRA_DIR}…"

API_BASE_URL=$(cd "$INFRA_DIR" && tofu output -raw api_url)

# demo_credentials is a sensitive map { email = password }
# Extract the first entry for the smoke-test default user.
CREDS_JSON=$(cd "$INFRA_DIR" && tofu output -json demo_credentials)
DEMO_EMAIL=$(echo "$CREDS_JSON" | jq -r 'keys[0]')
DEMO_PASSWORD=$(echo "$CREDS_JSON" | jq -r '.[keys[0]]')

cat > "$ENV_FILE" <<EOF
# ── Auto-generated by sync-env.sh — do not edit manually ────
# Re-run:  pnpm sync-env   (or ./sync-env.sh)

API_BASE_URL='${API_BASE_URL}'
SMOKE_EMAIL='${DEMO_EMAIL}'
SMOKE_PASSWORD='${DEMO_PASSWORD}'
EOF

echo "✓ Wrote ${ENV_FILE}"
